mode: train
training_stage: distance
init_ckpt: ./experiments/straightpcf_cvm_short5k_s123/checkpoint_2.pkl

model:
  frame_knn: 32
  feat_embedding_dim: 256
  decoder_hidden_dim: 64
  dsm_sigma: 0.01
  num_train_points: 1000
  num_modules: 2
  distance_embedding_dim: 128
  distance_hidden_dim: 64
  distance_ratio_loss_weight: 1.0
  distance_final_loss_weight: 200.0

data:
  input_dataset_dir: ./dataset_clean
  datalist: ./datalist/train_strat5k_seed123.txt
  use_prob: true
  num_files: 5000
  num_samples: 32768
  num_vertex_samples: 1024
  num_patches: 4
  patch_size: 1000
  batch_size: 4

optimizer:
  lr: 0.0001

trainer:
  epochs: 4
  max_grad_norm: 1.0
  exp_dir: ./experiments/straightpcf_core_short5k_s123
